Weather
hinataiswaifu/live pull request #39
Opened 2017-11-14 01:43 UTC by agentflare

2017-11-14 01:56 UTC, Jacqueuela approved these changes
LGTM

2017-11-14 01:56 UTC, Jacqueuela commented on Live/Classes/WeatherManager.cpp
> +        m_particle_generator = ParticleRain::createWithTotalParticles(100000);
Use preprocessor macros.

2017-11-14 01:56 UTC, Jacqueuela commented on Live/Classes/WeatherManager.cpp
> +    if(day % 10 == 0 && m_day < day) {
Faster day change.

2017-11-14 01:56 UTC, Jacqueuela commented on Live/Classes/WeatherManager.cpp
> +    if(day % 10 == 0 && m_day < day) {
On reroll don't restart animation.

2017-11-14 01:56 UTC, Jacqueuela commented on Live/Classes/WeatherManager.cpp
> +    m_weather_layer->removeChild(m_overlay);
removeFromParent

2017-11-14 01:56 UTC, Jacqueuela commented on Live/Classes/MapManager.cpp
> +MapManager::MapManager(Layer* game_layer) {
I still don't really think you need this, but whatever.

2017-11-15 22:13 UTC, sadmansk requested changes
Lemme know when it's ready.

2017-11-15 22:13 UTC, sadmansk commented on Live/Classes/MapManager.cpp
> +    weather_layer->setContentSize(Size(m_map_width, m_map_height));
Move weather layer logic to weather manager contructor.

2017-11-16 00:26 UTC, sadmansk approved these changes
lgtm

2017-11-16 00:27 UTC, merged